---
fit_bit:
  user_id: your_user_id
  client_secret: your_client_secret
  access_token: your_access_token
  refresh_token: your_refresh_token
hue:
  username: your_username
  ip: 10.0.0.15
  default_color: 15660
  gained_weight_color: 25500
  lost_weight_color: 65280
  same_weight_color: 46920
  default_sat: 100
  gained_weight_sat: 254
  lost_weight_sat: 254
  same_weight_sat: 254
  light_ids:
    - 1
    - 2
    - 3
    - 4
